namespace: bl-db-o-cru
appName: vdi-auth

appPorts:
- containerPort: 8000
  name: http

svcPort: 8000

nodeSelector: 
  oke.oraclecloud.com/pool.name: business_logic

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "512Mi"
    cpu: "500m"

hpaConfig:
  minReplicas: 5
  maxReplicas: 10
  cpuUtilization: 70
  memoryUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
