# Note: Need to create argocd-repo-creds-secret in the argocd namespace before deploying.

# Helm charts
---

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  {{- if eq .Values.environment "" }}
  name: lgm-components-appset
  {{- else }}
  name: "{{ .Values.environment }}-lgm-components-appset"
  {{- end }}
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: {{ .Values.repoUrl.templates }}
      revision: {{ .Values.repoBranch.templates }}
      files:
      - path: lgm/all-charts.yaml
  template:
    metadata:
      {{- if eq .Values.environment "" }}
      name: "{{"{{"}} .name {{"}}"}}"
      {{- else }}
      name: "{{ .Values.environment }}-{{"{{"}} .name {{"}}"}}"
      {{- end }}
      namespace: argocd
    spec:
      project: default
      sources:
      - repoURL: "{{"{{"}} .repoUrl {{"}}"}}"
        chart: "{{"{{"}} .chartName {{"}}"}}"
        targetRevision: "{{"{{"}} .targetRevision {{"}}"}}"
        helm:
          valueFiles:
          - "$values/lgm/values/{{"{{"}} .valuesFile {{"}}"}}"
      - repoURL: {{ .Values.repoUrl.templates }}
        targetRevision: {{ .Values.repoBranch.templates }}
        ref: values
      destination:
        server: https://kubernetes.default.svc
        {{- if eq .Values.environment "" }}
        namespace: "{{"{{"}} .namespace {{"}}"}}"
        {{- else }}
        namespace: "{{ .Values.environment }}-{{"{{"}} .namespace {{"}}"}}"
        {{- end }}
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
        automated:
          prune: true
          selfHeal: true


# k8s yamls
---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  {{- if eq .Values.environment "" }}
  name: k8s-component-addons-appset
  {{- else }}
  name: "{{ .Values.environment }}-k8s-component-addons-appset"
  {{- end }}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.repoUrl.templates }}
    targetRevision: {{ .Values.repoBranch.templates }}
    path: k8s-component-addons/
    helm:
      valueFiles:
      - values/values.yaml
      - ../values/values.yaml
      - ../values/{{ .Values.stage }}/lgm.yaml
      parameters:
      - name: "environment"
        value: "{{ .Values.environment }}"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

