certManager:
  basename: cert-manager
  certIssuerName: letsencrypt
  certIssuerEmail: cloudops.tpca@tallysolutions.com
  certIssuerServer: https://acme-v02.api.letsencrypt.org/directory
  hpa:
    enabled: flase
    minReplicas: 5
    maxReplicas: 10
    cpuUtilization: 70
    memoryUtilization: 80

envoy:
  basename: envoy

  publicLoadBalancer:
    type: nlb

  replicas: 2

  nodeSelector: oke.oraclecloud.com/pool.name=grafana
  podLabels:
    app.kubernetes.io/name: envoy

  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    cpuUtilization: 70
    memoryUtilization: 80

externalSecrets:
  basename: external-secrets

  hpa:
    enabled: flase
    minReplicas: 5
    maxReplicas: 10
    cpuUtilization: 70
    memoryUtilization: 80
