{{- if eq .Values.environment "" }}
{{- if .Values.externalSecrets.hpa.enabled }}
---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: external-secrets-hpa
  namespace: {{ .Values.externalSecrets.basename }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.externalSecrets.basename }}
  minReplicas: {{ .Values.externalSecrets.hpa.minReplicas }}
  maxReplicas: {{ .Values.externalSecrets.hpa.maxReplicas }}
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: {{ .Values.externalSecrets.hpa.cpuUtilization }}
          type: Utilization
      type: Resource
    - resource:
        name: memory
        target:
          averageUtilization: {{ .Values.externalSecrets.hpa.memoryUtilization }}
          type: Utilization
      type: Resource

{{- end }}
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.externalSecrets.basename }}-sa
  namespace: {{ .Values.externalSecrets.basename }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.externalSecrets.basename }}-cluster-role
rules:
- apiGroups: [ "" ]
  resources: [ "secrets" ]
  verbs: [ "get", "list", "watch" ]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.externalSecrets.basename }}-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: {{ .Values.externalSecrets.basename }}-sa
  namespace: {{ .Values.externalSecrets.basename }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.externalSecrets.basename }}-cluster-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.sharedSecretStore.name }}
spec:
  provider:
    kubernetes:
      remoteNamespace: {{ .Values.sharedSecretStore.sharedNamespace }}
      auth:
        serviceAccount:
          name: {{ .Values.externalSecrets.basename }}-sa
          namespace: {{ .Values.externalSecrets.basename }}
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: kube-system
{{- end }}