{{- range .Values.nats.streams }}
---

apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: {{ .name }}
  {{- if eq $.Values.environment "" }}
  namespace: {{ $.Values.nats.streamNamespace }}
  {{- else }}
  namespace: {{ $.Values.environment }}-{{ $.Values.nats.streamNamespace }}
  {{- end }}
spec:
  name: {{ .name }}
  allowDirect: true
  allowRollup: false
  denyDelete: false
  denyPurge: false
  discard: old
  duplicateWindow: 2m0s
  maxAge: ""
  maxBytes: -1
  maxConsumers: -1
  maxMsgSize: -1
  maxMsgs: -1
  maxMsgsPerSubject: -1
  noAck: false
  preventDelete: true
  replicas: 1
  retention: workqueue
  storage: file
  subjects: {{ .subjects }}

{{- end }}
