{{- if eq .Values.environment "" }}
apiVersion: v1
kind: Namespace
metadata:
  name: obs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: observability-agent
  namespace: fluent-bit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: observability-role
rules:
# 1. Access Kubernetes events
- apiGroups: [ "" ]
  resources: [ "events" ]
  verbs: [ "get", "list", "watch" ]

# 2. Read node labels
- apiGroups: [ "" ]
  resources: [ "nodes" ]
  verbs: [ "get", "list", "watch" ]

# 3. Read pod labels
- apiGroups: [ "" ]
  resources: [ "pods" ]
  verbs: [ "get", "list", "watch" ]

# 4. Access kubelet cadvisor
- apiGroups: [ "" ]
  resources: [ "nodes/proxy" ]
  verbs: [ "get", "list" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: observability-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: observability-role
subjects:
- kind: ServiceAccount
  name: observability-agent
  namespace: fluent-bit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-patcher
  namespace: fluent-bit
rules:
- apiGroups: [ "" ]
  resources: [ "pods" ]
  verbs: [ "patch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-patcher-binding
  namespace: fluent-bit
subjects:
- kind: ServiceAccount
  name: observability-agent
  namespace: fluent-bit
roleRef:
  kind: Role
  name: pod-patcher
  apiGroup: rbac.authorization.k8s.io
{{- end }}