{{- if eq .Values.environment "" }}
{{- range $lb := untilStep 0 (int .Values.traefik.publicLoadBalancer.count) 1 }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.traefik.basename }}-client-service-{{ add $lb 1 }}
  namespace: {{ $.Values.traefik.basename }}
  labels:
    app: {{ $.Values.traefik.basename }}
  annotations:
    oci.oraclecloud.com/load-balancer-type: {{ $.Values.traefik.publicLoadBalancer.type }}
    oci-network-load-balancer.oraclecloud.com/oci-network-security-groups: {{ $.Values.traefik.publicLoadBalancer.securityGroup }}
    oci-network-load-balancer.oraclecloud.com/node-label-selector: {{ $.Values.traefik.nodeSelector }}
spec:
  type: LoadBalancer
  ports:
  {{- range $port := untilStep 1 51 1 }}
  {{- $finalPort := add 11000 (add (mul $lb 50) $port) }}
  - protocol: TCP
    port: {{ $finalPort }}
    name: port{{ $finalPort }}tcp
  - protocol: UDP
    port: {{ $finalPort }}
    name: port{{ $finalPort }}udp
  {{- end }}
  selector:
    {{- toYaml $.Values.traefik.podLabels | nindent 4 }}

{{- end }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.traefik.basename }}-web-service
  namespace: {{ .Values.traefik.basename }}
  labels:
    app: {{ .Values.traefik.basename }}
  annotations:
    oci.oraclecloud.com/load-balancer-type: {{ .Values.traefik.publicLoadBalancer.type }}
    oci-network-load-balancer.oraclecloud.com/oci-network-security-groups: {{ .Values.traefik.publicLoadBalancer.securityGroup }}
    oci-network-load-balancer.oraclecloud.com/node-label-selector: {{ .Values.traefik.nodeSelector }}
spec:
  type: LoadBalancer
  ports:
  {{- if .Values.vdiAppListeners.enablePort80 }}
  - protocol: TCP
    port: 80
    name: port80tcp
    targetPort: 8080
  {{- end }}
  - protocol: TCP
    port: 443
    name: port443tcp
    targetPort: 8443
  selector:
    {{- toYaml .Values.traefik.podLabels | nindent 4 }}
{{- end }}